### ISSUE TITLE
Monitor - see all algo's

### ISSUE THREAD

**Issue by Riones** [nemosminer/NemosMiner-v2.5.2#342]
Hello. I can't see all algos that I have in my monitor.
How I do that?

Thank you.
![nemos](https://user-images.githubusercontent.com/36863608/36848354-eae6ca22-1d58-11e8-85dd-6b2c1701ffb7.jpg)

**Comment by Weeeishy** [comment]
Same. It only shows up in the first time you run the script, or after resetting the benchmarks.

**Comment by nemosminer** [comment]
Display Options

  Use -UIStyle Light or -UIStyle Full in start.bat
        Full = Usual display (Default)
        Light = Show only currently mining info 
  UIStyle automaticaly swtiches to Full during benchmarking.
In session display toggle

  Press key s in the window to switch between light and full display
  Press key e in the window to show/hide earnings 
  Will toggle(switch) display at next refresh
