### ISSUE TITLE
Donation function

### ISSUE THREAD

**Issue by trastek92** [nemosminer/NemosMiner-v2.5.2#346]
I have had it on 2 different machines where it runs the donation for hours rather than a few minutes, where is this setting adjustable? It isn't in the batch file anymore.  using Ahashpool, and ahashpoolplus.

**Comment by CaHek83** [comment]
if interval more then minute it donate much more, and after each restart of nemo (adding miners) donates again

**Comment by nemosminer** [comment]
@CaHek83 made interval 3mins now 
@trastek92 new version v2.5.2 fixes that were you using a master copy or last release v2.5.1 ?

**Comment by trastek92** [comment]
I was using master copy will reload. Much appreciated.
