### ISSUE TITLE
Idle miners list

### ISSUE THREAD

**Issue by CaHek83** [nemosminer/NemosMiner-v2.5.2#347]
Can you make like an older versions,
that we can see how many times and how long miners works
i know that in switching log contains this info but we need to group this info and making other calculations by myself. as for me as just user its difficult.

**Comment by jrafaelmdo** [comment]
@CaHek83 

RTFM: https://github.com/nemosminer/NemosMiner-v2.5.2/blob/master/README.md

Display Options

  Use -UIStyle Light or -UIStyle Full in start.bat
        Full = Usual display (Default)
        Light = Show only currently mining info

**Comment by CaHek83** [comment]
![screenshot_14](https://user-images.githubusercontent.com/35169315/36899247-e9d6cbfe-1e26-11e8-966b-03f34ded4fe4.png)

**Comment by nemosminer** [comment]
logs folder

**Comment by CaHek83** [comment]
in logs folder we have to  calculate all logs. very useful
