### ISSUE TITLE
HsrMiner does not start error 0xc000007b

### ISSUE THREAD

**Issue by silimaure777** [nemosminer/NemosMiner-v2.5.2#348]
Need help with Hsrminer, it just doesn't start. Trying to look on the web to find a solution but it still doesn't work... if someone had this problem and know what to do.

I got this error : hsrminer_neoscrypt_fork_hp.exe - Application error - (0xc000007b)

I've already insatalled DirectX 11 and it doesn't help.

**Comment by kevharper** [comment]
If you are overclocking, run your card(s) at stock speed instead and see if you get the error.

**Comment by silimaure777** [comment]
it doesn't work either

**Comment by kevharper** [comment]
what card(s) are you using?

**Comment by rvwoens** [comment]
same problem here. Not sure why it's closed. This error is given even when the exe is run without arguments, so probably the file is corrupt

**Comment by silimaure777** [comment]
Maybe that can help..., I’m running the exact same files on one of my other rig and it’s working so I don’t think the file is corrupted, it might be related to a software or dependency not installed yet on this rig, it would just be nice to know what it is.
